greenhouse:
  - https://boards.greenhouse.io/discord
  - https://boards.greenhouse.io/scaleai
  - https://boards.greenhouse.io/vercel

lever:
  - https://jobs.lever.co/caseware
  - https://jobs.lever.co/dnb

workable:
  - https://apply.workable.com/blueground/
  - https://apply.workable.com/persado/
  - https://apply.workable.com/skroutz/
