BEGIN;

ALTER TABLE public.external_matches
    ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS interview_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ NULL;

COMMIT;
